export const CITY_FETCH_INITIATED = 'CITY_FETCH_INITIATED';
export const CITY_FETCH_COMPLETED = 'CITY_FETCH_COMPLETED';
export const CITY_FETCH_ERROR = 'CITY_FETCH_ERROR';
export const CITY_SELECTED = 'CITY_SELECTED';
export const NO_STATE_SELECTED = 'NO_STATE_SELECTED';