export const PLACE_FETCH_INITIATED = 'PLACE_FETCH_INITIATED';
export const PLACE_FETCH_COMPLETED = 'PLACE_FETCH_COMPLETED';
export const PLACE_FETCH_ERROR = 'PLACE_FETCH_ERROR';
export const PLACE_SELECTED = 'PLACE_SELECTED';
export const PLACE_FETCH_EMPTY = 'PLACE_FETCH_EMPTY';
