export const STATE_FETCH_INITIATED = 'STATE_FETCH_INITIATED';
export const STATE_FETCH_COMPLETED = 'STATE_FETCH_COMPLETED';
export const STATE_FETCH_ERROR = 'STATE_FETCH_ERROR';
export const STATE_SELECTED = 'STATE_SELECTED';
export const STATE_FETCH_EMPTY = 'STATE_FETCH_EMPTY';